### ISSUE TITLE
AttributeError: module 'gradio' has no attribute ... 문제 해결

### ISSUE THREAD

**Issue by c2lv** [mlhub-action/sd-webui-launcher#6]
v.0.4.3과 v.0.4.7에서 해당 문제를 겪었습니다.  
혹시나 해당 문제로 어려움 겪고 계신 다른 분들 계실까 하여 공유 드립니다.  
11월 1일자로 gradio 버전 업데이트 되면서 발생한 문제 같네요.
최신 버전 gradio 말고 다운그레이드 버전 설치해주시면 됩니다.  
다른 부분 수정은 영향을 미치지 않은 것 같고, 430~431줄 아래와 같이 수정해보시기를 제안드립니다.

```
if not self.is_installed("gradio"):
            self.cmd('pip -q install "gradio==3.21"', check=True, live=True)
```

**Comment by huntchar** [comment]
격한 감사함을 표합니다

**Comment by sumof2primes** [comment]
v0.4.8 에서 호환되는 gradio 버전을  설치하도록 수정하였습니다
